on:
  schedule:
  # 00:05,12:05,18:05填报
    - cron: "10/10 4,10,16 * * *"
  push:

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1' # The Go version to download (if necessary) and use.
      - run: go run ./main/main.go 
        env:
            BUPT_USERNAME: ${{ secrets.BUPT_USERNAME }}
            BUPT_PASSWORD: ${{ secrets.BUPT_PASSWORD }}
